apiVersion: argoproj.io/v1alpha1
kind: Application
matadata:
  name: webcolor
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/vgip88/web-page-deploy.git
    path: k8s
    targetRevision: HEAD
  destination: 
    namespace: webcolor
    server: https://kubernetes.default.svc
