apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  sources: 
   - repoURL: https://prometheus-community.github.io/helm-char